### ISSUE TITLE
Toggle: crash on click if onChange is undefined

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#1008]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-4435865)

## description
`onChange` is optional, but `Toggle` crashes on click when it's `undefined`

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
https://github.com/buildo/react-components/blob/master/src/Toggle/Toggle.js#L59

there we should ensure that `requestChange` exists: `requestChange && ...`

## misc
{optional: other useful info}

**Comment by ascariandrea** [comment]
I don't know if checking against `requestChange` existence is the right thing in this case.
What is the purpose of a `Toggle`component that can't toggle?

Maybe we should set the `onChange` prop as *required* (and thus release a breaking change)

**Comment by FrancescoCioria** [comment]
> What is the purpose of a Toggle component that can't toggle?

I think we're using it somewhere like this:
- the `Toggle` is read only and does not have an `onChange`
- we change it's state with another trigger (like clicking on some text instead of the Toggle)

anyway, as we're already passing an empty function to handle this case I see no problem in making it required... also we wouldn't even need a breaking release as it's implicitly required right now (it crashes without `onChange`) so it's more a fix than an API change

**Comment by ascariandrea** [comment]
The `onChange` is optional cause the user can pass either `onChange` or `valueLink` (that has the required `requestChange` callback). Thus, if we want to make `onChange` required we should remove the `valueLink`, which is also a deprecated pattern, but this lead to a breaking change.

**Comment by giogonzo** [comment]
remember that typings can be more precise, e.g. `{ valueLink } | { value, onChange }`

**Comment by ascariandrea** [comment]
@giogonzo Sure, but I'm quite sure we're not passing `valueLink` prop to `Toggle` anywhere, so maybe we can remove this "feature" to have just one way to control this component through `onChange` and `value`.

**Comment by giogonzo** [comment]
yes, valueLink is quite dead

**Comment by FrancescoCioria** [comment]
> Sure, but I'm quite sure we're not passing valueLink prop to Toggle anywhere, so maybe we can remove this "feature" to have just one way to control this component through onChange and value.

@ascariandrea 👍
