### ISSUE TITLE
Showroom: Dropdown showroom example shows wrong example

### ISSUE THREAD

**Issue by ecamellini** [buildo/react-components#1015]
## description

Sometimes, changing component with an example left open results in the following behaviour, where the example rendered is correct but the code is from another component's example:

![image](https://user-images.githubusercontent.com/6418684/28714670-b5a8b08c-7394-11e7-8557-794643e205c9.png)

![image](https://user-images.githubusercontent.com/6418684/28714740-180fab86-7395-11e7-9125-c1f4b03f9be9.png)

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
this was fixed long ago (I can't remember the commit... sorry)
