### ISSUE TITLE
Don't use `t` from tcomb-react

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#1048]
## description
We should be using `t` from `tcomb` directly as it has a type definition file for TS.

**Comment by FrancescoCioria** [comment]
Wait, I remember we were using `tcomb` and then switched to `tcomb-react` for a good reason. Let me check

**Comment by FrancescoCioria** [comment]
The issue was that, by defining `tcomb` in our libs (like brc) we could have ended with multiple versions of `tcomb` in our final project. Maybe it's no longer an issue, I don't know
