### ISSUE TITLE
[TextOverflow] Text ellipsis but no text ellipsis method called

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#107]
We experienced a bug on Labonline where setting a width of a box with TextOverflow component inside leads to an ellipsis of text, but not the popover shown.

~~https://github.com/buildo/react-components/blob/master/src/text-overflow/TextOverflow.js#L35~~ (No more valid line)

Maybe this should change and check for minor and **equal** `offsetWidth`.

**Comment by FrancescoCioria** [comment]
@ascariandrea @giogonzo @francescogior is this bug still visible? should we make the change described above?

**Comment by giogonzo** [comment]
not currently as we added / removed 1px to the container size to fix this. Very minor
