### ISSUE TITLE
[Popover] Popover.popover.dismissOnClickOutside is too fragile

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#109]
See for instance: https://github.com/buildo/hailadoc/pull/1400#discussion_r45472408

Basically, as you're listenting for click on `window`, anyone else could intercept that event before the dismiss handler..

We could use a transparent overlay (same as in Dimmer), but this will prevent actually clicking on other things on the page (first click closes the popover, second click will actually work)

I know you both have opinions about this @FrancescoCioria @francescogior

**Comment by francescogior** [comment]
> We could use a transparent overlay (same as in Dimmer), but this will prevent actually clicking on other things on the page (first click closes the popover, second click will actually work)

I think this would be ok, `PanelMenu` works in this way

**Comment by FrancescoCioria** [comment]
I didn't find any solution to that problem...
this might help understand why this happens: http://stackoverflow.com/questions/1009753/pass-mouse-events-through-absolutely-positioned-element

**Comment by giogonzo** [comment]
I guess using `pointer-events` you also loose the ability to actually intercept the click yourself and close the popover..

I think the best we can do is to support both solutions and let the user decide with a prop from case to case..

About which one should be the default solution, I think this one (transparent overlay) because it's safer (at least you can be sure the popover will close correctly)

**Comment by FrancescoCioria** [comment]
Closing as in the end we opted for the already implemented version. If we'll ever reconsider this situation we can open a new issue :)
