### ISSUE TITLE
transitionStyles should be a required prop for Toaster

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#111]
<img width="499" alt="screen shot 2015-11-20 at 5 13 07 pm" src="https://cloud.githubusercontent.com/assets/2643520/11304845/1d70f04c-8faa-11e5-866b-a97b17922394.png">

...or it should have its own defaults for those?

Anyway, transition wrapper expects it

**Comment by FrancescoCioria** [comment]
ok, I think I made a bit of confusion here... the fact is: at first `transitionStyles` was required as it was the only way to add animations, then I also added the standard animation utility classes (`.entered`, `.entered.active` ...) so now it shouldn't be required anymore. (we need classes if we want to have different animations for parent and children, as we probably do for modals...)
