### ISSUE TITLE
[Popover] wrong positioning when hidden

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#112]
## requirements
the popover should be positioned correctly also when `visibility: hidden` so to avoid corruption of window size

## specs
when the poopver is not open:
- render a hidden version of the popover (`visibility: hidden`)
- wrap it in a div with:
  - absolute positioning
  - no size (no width and no height)
  - overflow hidden
this way the hidden popover will not affect the app layout in anyway

EDIT 26 Nov

**Comment by giogonzo** [comment]
seems fairly complex.. are you sure we can't just render `null` (or `display: none`) and postpone measurement and positioning at first actual render?

**Comment by FrancescoCioria** [comment]
I guess we could, but this means we need two render each time we show it.
Also, if we really want to support changes to content while open, we should recompute size after any prop change as it may modify its size...

**Comment by giogonzo** [comment]
> Also, if we really want to support changes to content while open, we should recompute size after any prop change as it may modify its size...

this is not happening now and I think the requirement on the user to have "stable" width in their popover layout is ok

> this means we need two render each time we show it.

Not if the above holds true (we need a 2 pass render the first time but then dimensions should be known?)

**Comment by FrancescoCioria** [comment]
@giogonzo solved the issue with a css trick: when invisible render the popover inside a div with no size and overflow hidden -> the popover is rendered (so we can measure its size) but it has no effect on the surrounding layout.
