### ISSUE TITLE
Dropdown: remove simpleValue prop

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#1126]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-4569587)

## requirements
having two ways to pass a `value` to `Dropdown` is confusing.
as `simpleValue` is no longer supported by `Select` we should remove that option.

## specs
remove `simpleValue` prop

## misc
{optional: other useful info}

**Comment by veej** [comment]
@FrancescoCioria I think this can be closed after the upgrade to react-select@2
