### ISSUE TITLE
Dropdown: clearing returns `null` to `onChange` when `multi = true`

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#1133]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-4626710)

## description
When hitting the `clear` icon with `multi = true` `onChange` receives `null`.
When removing the last element "manually" `onChange` receives empty string.

**Comment by FrancescoCioria** [comment]
IMO `null` is the correct behavior -> let's always return `null` when value is removed for any reason
