### ISSUE TITLE
[Typo] TextOverflow popover.event type

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#1139]
← #1034

## requirements
```tsx
TooltipRequiredProps = {
  // ..
  /** popover props */
  popover: ObjectOverwrite<PopoverProps.Popover, {
    content: string,
    event?: undefined // <- this is causing some issues on Alinity PRO
  }>
  // ...
```

## specs
use a more proper `ObjectOmit`

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
This should actually be fixed directly in alinity pro:
the issue here is that the `&` in alinity pro is not correctly overwriting the prop `event`.

See the branch `typo-brc` in alinity pro for a possibile fix I made
