### ISSUE TITLE
Dropdown shows a vertical white line when not `searchable`

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#1159]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-5868348)

## description
Introduced by upgrading to `react-select@1.0.1`
<img width="192" alt="screen shot 2017-11-27 at 11 10 26 am" src="https://user-images.githubusercontent.com/2643520/33261766-2bd4657e-d364-11e7-8962-0932c56eaf77.png">

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by veej** [comment]
@giogonzo I think this can be closed after the upgrade to react-select@2

**Comment by giogonzo** [comment]
I guess
