### ISSUE TITLE
Icon color props doesn't seem to have any effect

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#1172]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-6881317)

## description
Changing the `color` props of an `Icon` doesn't alter its color.

## how to reproduce
![](http://g.recordit.co/4JePHkEeiG.gif)

## specs
A quick investigation shows that the color is set on the `.icon` class but the one on the `icon::before` pseudo-class prevails

**Comment by giogonzo** [comment]
outdated, we have SVG icons now. Closing for the moment, if there's a similar issues with SVG icons, it will probably be related to #1258
