### ISSUE TITLE
Unable to install component separately 

### ISSUE THREAD

**Issue by divyenduz** [buildo/react-components#1185]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-7685854)

I tried to follow the [getting started guide](http://react-components.buildo.io/#getting-started) to install the [Textarea Autosize](http://react-components.buildo.io/#textareaautosize) component separately but it yielded an error for me with both `yarn` and `npm`. 

`yarn add @buildo/react-textarea-autosize` OR `npm install --save @buildo/react-textarea-autosize`

Detailed output:-
```
divyendusingh [k-website]$ yarn add @buildo/react-textarea-autosize                                             [2/41]
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@buildo%2freact-textarea-autosize: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/divyendusingh/Document$/projects/o/k-website/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
divyendusingh [k-website]$ npm install --save @buildo/react-textarea-autosize
npm ERR! code E404
npm ERR! 404 Not Found: @buildo/react-textarea-autosize@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/divyendusingh/.npm/_logs/2018-02-25T11_25_07_276Z-debug.log
```

Maybe the docs are outdated or I am doing something wrong. Can you please help me out. 

P.S. thanks for the awesome set of components.

**Comment by FrancescoCioria** [comment]
Hi @divyenduz 
sorry, actually at the moment only a few set of components is published separately, the package at the top is mocked (i forgot to hide it).

Luckily, TextareaAutosize is one of the few that are published separately :)
You can find its repo here: https://github.com/buildo/react-autosize-textarea
and install it like this:

```sh
npm install --save react-autosize-textarea
# or
yarn add react-autosize-textarea
```

I'll remove those wrong package names for now.
PS: We're planning to publish every component separately very soon.

**Comment by divyenduz** [comment]
Thanks, I am closing this issue as your comment resolves it for me.
