### ISSUE TITLE
Button: label static vs. runtime prop differ, potentially causing undesired tcomb errors in console

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#1264]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-11968038)

## description
For TS, all keys are optional: https://github.com/buildo/react-components/blob/master/src/Button/Button.tsx#L46

But if `processing` is not passed, a tcomb error message appears

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
@giogonzo I cannot reproduce this error:

![image](https://user-images.githubusercontent.com/4029499/50011329-1a997800-ffbc-11e8-990e-dbc36fa05f44.png)

**Comment by FrancescoCioria** [comment]
@giogonzo ping

**Comment by giogonzo** [comment]
This is the original error on the project:
![image](https://user-images.githubusercontent.com/6418684/42519581-a1d50b82-8464-11e8-92d4-166311359d0b.png)
Which has now been fixed by providing more labels to the button

Re-reading this, I think the only issue here is that `Button` is defaulting some labels (ready and not-allowed) but not others (processing, success and error) so this caused some confusion.

The issue about the types (static and runtime) not being coherent instead seems not valid: `t.dict(Domain, Codomain)` produces a dictionary with optional keys in the domain -> same as using `Partial<>`, am I right? But at the same time, looking at the error above this seems not true 🤔 

I'm confused, and probably something has changed in Button source code on this repo in the meantime, but since we can't reproduce, I would ignore this for the moment
