### ISSUE TITLE
TextareaAutosize shows invalid package import in the styleguide

### ISSUE THREAD

**Issue by hinok** [buildo/react-components#1292]
[Project card](https://github.com/buildo/react-components/projects/1?fullscreen=true#card-16200860)

Hey,
https://react-components.buildo.io/#textareaautosize shows invalid import to a different package that is named very, very similar and does the same thing. It took me a few minutes to understand why `rows={N}` prop doesn't work me... - I've installed package `react-textarea-autosize` not `react-autosize-textarea`.

Your package: https://www.npmjs.com/package/react-autosize-textarea
Not your package: https://www.npmjs.com/package/react-textarea-autosize

**Expected**

```
import TextareaAutosize from 'react-autosize-textarea'
```

**Current result**

```
import TextareaAutosize from 'react-textarea-autosize'
```

![zrzut ekranu 2019-01-4 o 22 02 59](https://user-images.githubusercontent.com/1313605/50710958-cb031500-106c-11e9-8a62-a8b2a405cc8d.png)

**Comment by FrancescoCioria** [comment]
Ups, thanks for the report @hinok !

**Comment by FrancescoCioria** [comment]
fixed in https://github.com/buildo/showroom
