### ISSUE TITLE
[Dropdown] export react-select style from /dropdown

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#133]
## requirements
- facilitate import of needed style
- make it more clear that this component comes with a `css` file
- follow our (soon to be) sass name convention: `camelCase` version of the component name (refer to point in #204 )

## specs
manually copy `node_modules/react-select/dist/default.css` to `dropdown/dropdown.scss`

[EDITED]

**Comment by nerder** [comment]
@FrancescoCioria what is `postinstall` ? You mean one of the scripts already present on `package.json`?

**Comment by FrancescoCioria** [comment]
sorry, this Issue is old (we were not installing from `github#master` at that time...)

For now, as we have fixed the version of `react-select`, you could simply manually copy
`node_modules/react-select/dist/default.css` to `dropdown/style.css`

We'll think of a way to automatize this when we'll have the need (translated: when we update `react-select`)
