### ISSUE TITLE
[Showroom] EmptyPlaceholder example not working

### ISSUE THREAD

**Issue by ecamellini** [buildo/react-components#1392]
![image](https://user-images.githubusercontent.com/6418684/68676019-5edd2180-0559-11ea-9a81-30accb42038c.png)

**Comment by Cardu** [comment]
@ecamellini  I think that `EmptyPlaceHolder` should not import it's own scss, if I try to use it in a project, I have this error:

![image](https://user-images.githubusercontent.com/4497461/68776025-b352d080-062f-11ea-88df-59a5103a5fcd.png)
