### ISSUE TITLE
DatePicker should have clearable option

### ISSUE THREAD

**Issue by Cardu** [buildo/react-components#1423]
At the moment, it's always clearable. It should give the option to be or not, like the dropdown.

There is a simple workaround, but the data type can still be null:

```
.SingleDatePickerInput .SingleDatePickerInput_clearDate {
          display: none;
}
```

**Comment by veej** [comment]
`breaking` label added. @aSlug remember to do this for every breaking issue, so that `smooth-release` can infer the right semver
