### ISSUE TITLE
proposal: stop pinning dependencies

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#1430]
I believe pinned deps (no `^`) is just a leftover form the pre-lockfile era (ages ago)

**Comment by gabro** [comment]
I’m very much in favor of this. Using ^ is a recipe for bugs and we should always use `yarn add --exact`

**Comment by giogonzo** [comment]
wait, are you saying the opposite?
Currently BRC deps are declared like `"dep": "1.2.3"`, my proposal is to have them declared as `"dep": "^1.2.3"` and have the final projects lock versions as they wish using a lockfile and/or yarn resolutions if needed

**Comment by gabro** [comment]
Ah sorry, I was saying the opposite but it probably makes sense for apps not libraries

**Comment by giogonzo** [comment]
> it probably makes sense for apps not libraries

yes, I agree
