### ISSUE TITLE
componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by MalpenZibo** [buildo/react-components#1435]
## Description
I get a Warning: componentWillReceiveProps has been renamed ..... Please update the following components: Select.

Maybe is related to this issue? https://github.com/JedWatson/react-select/issues/3720

## Log
```
react-dom.development.js?61bb:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Select
```

**Comment by aSlug** [comment]
In addition to the dependency there are several points in the code where `componentWillReceiveProps` is still used.
If we are 100%  confident on keep using it we can just use the new name `UNSAFE_componentWillReceiveProps` (also the old name would stop working with React 17), but would be better to refactor the code to completely avoid it.

**Comment by giogonzo** [comment]
I would just go with `componentDidUpdate` for the moment, I doubt there are real cases in the codebase where this makes any real difference compared to using `WillReceiveProps`
