### ISSUE TITLE
[showroom] evaluate how to move stuff from revenge to buildo

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#147]
pros:
- revenge react components doesn't really make much sense, since the only dependency they have on revenge is `@pure` and `@skinnable`
- give relevant components a life of their own (with their own repo)

cons:
- some work to do
  - create a default, blank style and override it in labonline (future)
  - fix and test labonline
- code duplication for `@pure` and `@skinnable`

**Comment by FrancescoCioria** [comment]
@giogonzo opinions?

**Comment by giogonzo** [comment]
as already discussed offline, nothing more to add, I'm ok with moving

Rationale for a separate repo was: in `b-r-c` we have components ready to be used by third parties, in `revenge-r-c` just for internal use. Now that this is not true anymore, it makes no sense to have them in separate repos
