### ISSUE TITLE
add shrink to FlexView

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#16]
@FrancescoCioria 

I would need to set all the flex components for a specific view, ex: `flex: 1 1 100%;`.
Could we add a `shrink` prop to achieve this?

Come back soon, we miss you!

**Comment by FrancescoCioria** [comment]
Do we want it to accept a ```number``` like ```flexBasis``` or to be more co,plex like the ```grow``` property which can accept a ```bool``` and in that case defaults to ```flex: 1 0 100%``` (or something else)

Of course the other keys may be overridden by ```flexBasis``` and ```grow```
@giogonzo

**Comment by giogonzo** [comment]
Adding it myself because I need it now :P

I'd say `shrink=true` and `shrink=number` will shortcut `getShrink()` and return `1` or `number` respectively

**Comment by FrancescoCioria** [comment]
nice!
