### ISSUE TITLE
Button should be usable with other events other than 'click'

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#177]
# requirements
- at the moment, in order to use the button with a custom event (submit/keyup actually) one should duplicate the logic in `ButtonLogic`
- `Button` (`ButtonLogic`) api should instead allow in some way different events in order to avoid this duplication

# specs
- TODO

**Comment by FrancescoCioria** [comment]
@francescogior ping

**Comment by FrancescoCioria** [comment]
closing for now
