### ISSUE TITLE
implement `DateInputs` (better name?)

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#219]
on Hailadoc (https://github.com/buildo/hailadoc/issues/1646) @ascariandrea made a first working example of this component but, as we were on a hurry, we didn't carefully define requirements nor specs. The result is a working component but not general enough (nor safe, I guess?) to be moved on this repo.
So, let's define requirements and specs :)
## requirements
- should have the standard API for form fields: `value`, `onChange`, `valueLink`
- should work out of the box with `tcomb-form`
- if possible, we'd better avoid using `momentJS`
  - find a replacement for date validation...
- user passes and receives only one value (specs might be: `Date`, `null` or `Error`), he shouldn't care about `day`, `month`, `year`
- labels (**TODO**)
  - general label?
  - label for each input?
- status (**TODO**):
  - valid
  - on focus
  - not valid (single input validation too?)

**Comment by FrancescoCioria** [comment]
@lucacioria @alessandravilla please help us with UX / UI (like the labels and status points of the requirements)

**Comment by lucacioria** [comment]
about using `Date` let's have a chat with @francescogior and @giogonzo ... Java Date and js Date behave differently (java is more of a historian) and can lead to inconsistencies.

**Comment by FrancescoCioria** [comment]
I think this component shouldn't care too much about it: it's the user the one responsible to parse the date string returned from the API. Also, contrary to `rc-datepicker`, this component won't have any format related problem as each date part will have its own input field (`day`, `month`, `year`). The only issue I see is related to ISO/not-ISO parsing: browsers process differently `yyyy/mm/dd` (locale time) from `yyyy-mm-dd` (ISO -> UTC time).
As this problem is easier to isolate, I think we could simply use the first one (supported by every browser since the beginning) to generate a `Date` with browser time.

what do you think @giogonzo? should we require `value` to be an ISO string instead?

**Comment by lucacioria** [comment]
I was talking more about weird cases in the past, not sure how relevant. Maybe stuff like the 29th of february didn't exist in bangladesh in 1924...
