### ISSUE TITLE
package import is too verbose

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#24]
right now this is the standard way to import a package:
```
import LoadingSpinner from 'buildo-react-components/lib/loading-spinner';

require('buildo-react-component/lib/loading-spinner/style.css');
```

I think we should:
- export each lib directly from the main `index.js` so to achieve: `import {LoadingSpinner} from 'buildo-react-components';`

**Comment by francescogior** [comment]
:+1: 

as a sidenote,
````
import 'some-stylesheet.scss';
````
works as well

**Comment by FrancescoCioria** [comment]
I discovered I was already exporting packages directly from main `index.js` but as I had forgotten about this it was buggy and incomplete. I fixed it in the PR
