### ISSUE TITLE
react 0.14 compatibility

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#244]
It's time to make the leap!

What are the main concerns?

**Comment by FrancescoCioria** [comment]
it should keep working on every `0.13.3` project we're still maintaining :)

**Comment by gabro** [comment]
Good point. I think it should just be a matter of fencing the refs accesses behind a common function (what giulio did in one of our components I think).

**Comment by FrancescoCioria** [comment]
yes, here: https://github.com/buildo/react-autosize-textarea/blob/master/src/TextareaAutosize.js#L21-L23

PS: `React.findDOMNode` works both in 0.14.x and 0.13.3, that catch is it throws a big red warning in 0.14.x

**Comment by FrancescoCioria** [comment]
brief list of things we should do/verify before passing to 0.14.x
- util function `getDOMNode(ref)` to get a `ref` node without warnings/errors
- context wrappers should keep working in 0.13.x -> (we should simply leave them untouched)
- stateless functions can't be used
- we must improve are examples to easily test both 0.13.x and 0.14.x
