### ISSUE TITLE
Date picker: defect on Safari and Chrome

### ISSUE THREAD

**Issue by gcanti** [buildo/react-components#251]
Safari Version 9.0 (9537.86.1.56.2)
Chrome Version 48.0.2564.97 (64-bit)

From the showcase:

<img width="538" alt="date-picker" src="https://cloud.githubusercontent.com/assets/878912/12789073/94eee520-ca9c-11e5-8be5-71502d1a9e19.png">

**Comment by FrancescoCioria** [comment]
I opened an issue on [`rc-datepicker`](https://github.com/buildo/rc-datepicker/issues/68)
thank you
