### ISSUE TITLE
revert #233/#234 once babel recognizes that again

### ISSUE THREAD

**Issue by flying-sheep** [buildo/react-components#259]
https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-177720642

**Comment by FrancescoCioria** [comment]
Hi @flying-sheep 
From what I read on your link I understood that:
1) The community is still confused about semicolons on class static properties (are we sure this is the final word?)
2) semicolons on class static properties may be soon optional (again)

Still, as they're not yet (https://github.com/babel/babel/pull/3225) I'd rather keep those harmless semicolons for now :)

Thank you for informing us about this update!

**Comment by flying-sheep** [comment]
> The community is still confused about semicolons on class static properties

[here is a summary](https://github.com/jeffmo/es-class-fields-and-static-properties/issues/26#issuecomment-171587367)

> are we sure this is the final word? […]

class properties aren’t and never were intended as ASI exceptions. this was a misunderstanding which is now resolved. so yes.

> semicolons on class static properties may be soon optional (again)

yes.

> Still, as they're not yet (babel/babel#3225) I'd rather keep those harmless semicolons for now :)

sure, this is intended to be resolved once a babel release has that.

**Comment by flying-sheep** [comment]
OK, [6.5.2](https://github.com/babel/babel/releases/tag/v6.5.2) has it reverted!

**Comment by gabro** [comment]
we decided to stick to semicolons.
