### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by nerder** [buildo/react-components#277]
## Requirements
- Name: `TimePicker`
- There should be an input form
  - it can be manually filled
    - input will be validated
    - should support 1min interval
  - can be filled selecting from a dropdown list
    - each item of the list should have 30min interval
- The value can support both 24h and 12h time formats
- There should be a placeholder on empty values
- Values can be typed in in multiple ways

## Specs
- `TimePicker` is a self closing JSX tag, doesn’t accept any child
- It will wrap a  `Dropdown` from `b-r-c`
- `value` is an Object composed by `hours` and `minutes`
- When the user start typing the `Dropdown` will be filtered
- The dropdown list will include only times between [min..max]
- The interval (aka step value) is fixed to 30 min, because smaller intervals would lead to a poor UX
- Seconds are not handled
- Choose one of the item from the list will override user typed one
- The manually typed input have to be validated (if is not part of the option list already or it can be)
  - This is a validation for 12h
    - `^([1-9]|1[0-2])[:,\.\|\/\\]?([0-5]\d)?\s*?(AM|PM)$`
  - This is a validation for 24h
    - `^([01]\d|2[0-3])[:,\.\|\/\\]?([0-5]\d)?$`
- If the input validation failed, the input will become red ( or something)
- the placeholder will be a string that not have to be validated

## API [Draft]
```javascript
<TimePicker 
  value={Object}
  min={Object}
  max={Object}
  format={Enum}
  placeholder={String}
/>
```
## Defaults
**value**: `undefined`
**min** : `undefined`
**max** : `undefined`
**format** : `24h`
**placeholder** : ``

**Comment by giogonzo** [comment]
why `min` and `max` as strings? did we discuss how values are passed to this component?

also, why no `value` (or `hours` and `minutes`) prop?

**Comment by giogonzo** [comment]
also I left some comments on the original Paper

**Comment by FrancescoCioria** [comment]
REQUIREMENTS:
> input will be validated

I think we also agreed on some form of autocompletion

> There should be a placeholder on empty values

Why? I don't really like having a default for `placeholder`

DEFAULTS:
I think the default format should be `24` as it's the ISO standard.
Also, as already said, I would remove the default for `placeholder`.

**Comment by nerder** [comment]
List of cases:
--

**Comment by nerder** [comment]
## Requirements question

Separator have to be parametric?

/cc @lucacioria @FrancescoCioria @giogonzo

**Comment by FrancescoCioria** [comment]
> Separator have to be parametric and customizable by the user?

Not relevant for now. This feature can be easily added in the future if we ever need it.

I say we simply hardcode a list of valid separators.
```js
const separators = [
  ':',
  '.',
  ',',
  '-',
  '/',
  ' '  // empty space
];
```

@lucacioria did I forget any useful separator?

**Comment by lucacioria** [comment]
seems ok to me, are you including the "no separator"? such as `1233` => `12:33`? It's not very important, just asking

**Comment by nerder** [comment]
@lucacioria yes, that feature is already there ;)

**Comment by giogonzo** [comment]
Some corrections/specifications inline:

> List of possible cases:
> - undefined => all the list

(1) undefined  (or empty) => all the list generated considering interval

> - H => list filtered starting from the first letter (i.e input `1`; output: all the elements that starts with 1)

(2) the list above (1), filtered starting...

> - HH => same as H but more specific (i.e input `12`; output: all the elements that starts with 12)

(3) the list above (1), but more specific...

> - HH: => same as HH, shows all the available interval options (ie input `12`; output: all the variant of 12, like 12:30, 12:00, 12:15 etc)

(4) same as 3

> - HH:m => doesn't show nothing if the `m` is not the start letter of one of the interval options

(5) I'd change this in: if `m` start a valid interval-generated value, just show this single one. If not, we can choose, but the easier option for now is just to complete with a `0` as second minute

> - HH:mm =>  Show just the element requested, no result instead (am/pm version for 12h timeFormat)

(6) HH:mm =>  Show just the element requested, plus the `pm/am` split if it is current time format

> Special input cases:
> - HH[symbol]mm => will be automatically converted to HH:mm (*symbols are: ,[space].|\/)
> - Hmm => will be autocamically expressed as H:mm
> -HHmm => will be automatically expressed as HH:mm

seem good to me

> Undefined behaviour:
> - HH:m => what the list have to show? (proposal: variants of HH:m0)

see (5)

In addition, in every case we should complete for am/pm versions if it is the current time format

Am I missing something?

/cc @FrancescoCioria
