### ISSUE TITLE
implement Accordion

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#279]
## requirements
should be
- stateless
- content:
  - icon on the left (optional)
  - title
  - state indicator icon on the right (defaults to arrows)
- different style if open
- different style if selected
- all clickable

## specs
API:
- `isOpen: t.Boolean`
- `isSelected: t.maybe(t.Boolean)`
- `onChange: t.Function`
- `onOpen: t.maybe(t.Function)`
- `onClose: t.maybe(t.Function)`
- `header: t.ReactChild` (if you want a left icon you can pass `<FlexView>{icon} {title}</FlexView>`)
- `children: t.ReactChildren`
- `icons: t.struct({ open: t.String, closed: t.String )}`

NB: custom className for `open` and `selected` state not in this iteration (as usual we'll do this when required)

EDIT: replaced `content` with `header`

**Comment by FrancescoCioria** [comment]
> content: t.ReactChild

@giogonzo do you understand this? do you think it would be better as `header`?

**Comment by giogonzo** [comment]
so this is a single element in the accordion, and the entire sidebar would be a list of these?

> do you think it would be better as header?

yes, `header` or `title` are more clear to me

**Comment by FrancescoCioria** [comment]
> so this is a single element in the accordion, and the entire sidebar would be a list of these?

yes

ok, going for `header` (we always used `title` as a `t.String`... might be confusing having it as `t.ReactChild`)
