### ISSUE TITLE
Lint errors fix

### ISSUE THREAD

**Issue by nerder** [buildo/react-components#281]
## requirements
Clean the code base

## specs

- run `npm run lint` it will fix a lot by itself
- fix the remaining issues

## Note

As you can see `travis-ci` will fail because of an `eslint` rule, specifically `prefer-es6-class`. It will happen because we still have some `React.createClass` instead of ES6 classes, as discussed offline with @giogonzo i can leave it like that atm. So the TBD points here are: we have to 'relax' ESlint (using rules ignoring comments for instance) or just remove that rule?

cc @gabro @FrancescoCioria

**Comment by gabro** [comment]
We can relax eslint for b-r-c, but I'd like to hear from @giogonzo why not change `createClass` now?

**Comment by FrancescoCioria** [comment]
The components using `React.createClass` are all obsolete and should be removed soon (I'm referring to `FlexCell`, `Menu` and `PanelMenu`)

In particular `FlexCell` is currently being used in LOL. Passing from `React.createClass` to ES6 `class` may cause bugs when using `this.refs.{REF}`. As we're going to delete all three components I suggest we simply ignore them for now and instead open an issue to remove/replace them.

**Comment by gabro** [comment]
Ok, so my take is: let's simply ignore the CI fail and move on with #282

**Comment by nerder** [comment]
Done

**Comment by giogonzo** [comment]
for the next time, you can disable only specific rules with `// eslint-disable-line package/rule`

**Comment by FrancescoCioria** [comment]
Sorry, I didn't notice that in the PR
