### ISSUE TITLE
remove FlexCell, Menu and PanelMenu

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#286]
## requirements
all of them are obsolete and shouldn't be used (I think only `FlexCell` is currently being used)

## specs
verify if component is being used:
- yes -> fix projects then remove
- no -> remove

EDIT: the `Menu` this issue refers to is the sub-component used by `PanelMenu`. [this one](https://github.com/buildo/react-components/blob/master/src/panel-menu/components/Menu.js)

**Comment by francescogior** [comment]
Wait! `Menu` is used in `Labonline`

**Comment by FrancescoCioria** [comment]
I think you are using the `Menu` from `DropdownMenu`.
The one I was referring to is a sub-componet of `PanelMenu` (sorry, I didn't realize there were two)

**Comment by francescogior** [comment]
Oh... right!
