### ISSUE TITLE
[showroom] simplify deploy

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#294]
## requirements
simplify deploy steps, if possible automate them.
currently I have to do this:
- `gco master`
- `git pull`
- `gco gh-pages`
- `git pull` (for safety)
- `git merge master`
- update `components.json`
- `npm run deploy-showroom`

## specs
apart from *update `components.json`* everything could be automated with a simple alias.
- [x] automate sync between `showroom/components.json` and `examples/components/index.js` #295 
- [x] create single command to automate every step https://github.com/buildo/react-components/commit/1d2cb669279a70c809fa2f1b854af51a84c796ff
- [ ] if possible call it with some hook after `push` on `master`?

**Comment by FrancescoCioria** [comment]
@gabro do you have any suggestion for the last point?

**Comment by FrancescoCioria** [comment]
@gabro me want DroneCI!!

**Comment by gabro** [comment]
book me some time this week ;)

**Comment by FrancescoCioria** [comment]
closed by #383

**Comment by gabro** [comment]
:tada:
