### ISSUE TITLE
components should accept 'id'

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#32]
EDIT: for now only the components for which we have the source (`flex` and `loadingSpinner`)

**Comment by gabro** [comment]
legit, but why?

**Comment by FrancescoCioria** [comment]
I especially needed it for `flex` as it acts as a replacement for `div` and in `oxway` we're using a lot of ids for analytics purposes

**Comment by gabro** [comment]
I see, thanks.
