### ISSUE TITLE
Popover is not shown/open when `popover.isOpen` starts `true`

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#334]
## description

rendering `Popover` `isOpen=true` doesn't show the popover as expected

## specs
In `componentDidMount`, if `this.isOpen()` is true, we should call `this.onPopoverOpenChange` which is already being used anywhere else in code.
(replace this: https://github.com/buildo/react-components/blob/master/src/popover/Popover.js#L54)

EDIT by Francesco
## misc

added an example here that exposes the defect behavior: https://github.com/buildo/react-components/tree/popover-initially-open

**Comment by FrancescoCioria** [comment]
looks like in `componentDidMount` instead of calling the correct function I'm handling it manually in the wrong way. It's probably some dead code of an older version: I updated the specs.
