### ISSUE TITLE
TimePicker: add support for `valueLink`

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#335]
## requirements
any standard form component should also accept a prop `valueLink` to be use instead of `onChange` and `value` (https://facebook.github.io/react/docs/two-way-binding-helpers.html)
This is useful when using `TimePicker` inside a form.

## specs
use `link-state` utils from https://github.com/buildo/react-components/tree/master/src/link-state

## misc
it should work like this:
```jsx
<TimePicker valueLink={this.linkState('myStateKey')} ... />
```

**Comment by gabro** [comment]
or not, `valueLink` has been deprecated.
