### ISSUE TITLE
[TextOverflow] Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#356]
## description

under certain circumstances, TextOverflow is trying to get the computed style of a `null` `React.findDOMNode` return value:
```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

## specs

for the time being, just patch it and hide the possibly-null access behind a check

**Comment by FrancescoCioria** [comment]
remember those `setTimeout`s? yeah...
