### ISSUE TITLE
add checkbox

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#4]

**Comment by FrancescoCioria** [comment]
@giogonzo can we kill this? I always hated this `Checkbox` :D
The problem about this component is that its style is hardly customizable and, as we're talking about a checkbox, style customization is the main (if not the only..) feature.

PS: also no one has ever asked me about its progress in 4 months!

**Comment by giogonzo** [comment]
I guess yes? There's no "native" and "web" in this project name
