### ISSUE TITLE
[DropdownMenu] Make DropdownMenu's Menu inner component customizable

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#411]
## requirements
- `DropdownMenu` should accept a custom **component** for `Menu`

## specs
- `DropdownMenu` props will change:
```js
@props({
 children: t.maybe(t.ReactChildren),
  menu: t.struct({
    menuRenderer: t.maybe(t.func([t.list(optionType)], t.ReactChild)),
    options: t.list(optionType)
  }),
  iconClassName: t.maybe(t.Str), // if children is passed, this is ignored
  isOpen: t.maybe(t.Bool),
  onOpen: t.Func,
  onClose: t.Func,
  dismissOnClickOut: t.maybe(t.Bool),
  size: t.maybe(t.enums.of(['small', 'medium', 'large']), ''),
  maxHeight: t.maybe(t.Num),
  className: t.maybe(t.Str)
})
```
The idea is to have a `menu.menuRenderer(options)` (function) prop that returns the custom component.

## misc
- We need to check which projects include this component to avoid breaking changes.

c/c @FrancescoCioria @francescogior @giogonzo

**Comment by FrancescoCioria** [comment]
I would leave `options` as a top-level prop and simply add `menuRenderer` function prop without `menu` prop (this is the same approach `react-select` uses).

for the rest I like the idea of having a `menuRenderer` callback

**Comment by giogonzo** [comment]
👍 makes sense

about flat vs. nested props probably yes, if there's no specific need (i.e *many* semantically nested props) I would stay in the flat world

**Comment by ascariandrea** [comment]
Ok, I proposed it to keep menu specific props isolated, but for compatibility also we are going for the flat version! 😎
