### ISSUE TITLE
Dropdown: multi value support is broken

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#423]
## description
The `value` passed to `react-select` [is computed](https://github.com/buildo/react-components/blob/master/src/dropdown/Dropdown.js#L86) with `valueToOption` function.

First of all, why?

Anyway, this breaks the `multi` selection feature. `valueToOption` looks for a matching value in the options, but - in the case of `multi` - `value` contains a list of comma-separated values.

## how to reproduce
![](http://g.recordit.co/cQMOZ3UNzY.gif)

i.e. perform a multiple selection on a controlled `Dropdown`.

## specs
I would just pass down `value` without calling `valueToOption`, but I'm sure there's a reason for that.
Anyone? @FrancescoCioria @francescogior @giogonzo?

Otherwise, we can just check for `multi` and pass the raw value only in that case.

**Comment by gabro** [comment]
this is the incriminated commit by the way

https://github.com/buildo/react-components/commit/84912af99e6e960472cec64cdb55747cc29e5a7b#diff-edd5be6eed72fd2e39bb04b199d23f29R58

**Comment by FrancescoCioria** [comment]
@francescogior is this issue still valid after the upgrade to react-select@1.0.0-rc1 or can we close it?

**Comment by francescogior** [comment]
Looking at the showroom http://react-components.buildo.io/#/sections/components/component/dropdown?openSections=%3Bcomponents it looks it works

![](https://i.gyazo.com/fcfc614607374878d3783b991bd120ee.gif)

imho you can safely close this
