### ISSUE TITLE
[Modal] Create a standalone Modal component

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#432]
## requirements
- unify several modal implementations we made in our projects
- have an isolated modal component

## specs
- use the labonline one as starting point

## misc
{optional: other useful info}

**Comment by gabro** [comment]
just to be clear, the first step we discussed offline is simply to port the labonline modal into BRC.

What do you mean by

> unify several modal implementations we made in our projects

?

**Comment by ascariandrea** [comment]
Yep, that's what I'm doing..
I meant I'm about to create a component that should be the only one used in our projects (not now, but in the near future)..
