### ISSUE TITLE
[Panel] should be clickable anywhere in collapsed state

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#433]
## description
- as for title, collapsible vertical panels in collapsed state have a small clickable area (the header) to expand them
- make all the panel area clickable (i.e. add onClick handler to panel-content in collapsed state)

**Comment by FrancescoCioria** [comment]
@francescogior why? who's asking for this? will this cause breaking changes?

**Comment by francescogior** [comment]
https://github.omnilab.our.buildo.io/buildo/aliniq/issues/2419

- no API changes
- it may break if somebody used custom content on the vertical `panel-content` in `collapsed` state (let's ask @gabro but I think 0,01% chance)

**Comment by FrancescoCioria** [comment]
> it may break if somebody used custom content on the vertical panel-content in collapsed state 

which means that we're breaking a feature with this issue, right? we should discuss this with alessandra first to be sure that it's fine having a stricter usage for the collapsed panel

**Comment by gabro** [comment]
fine for me
