### ISSUE TITLE
[TextOverflow] Should update also on parent resize

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#436]
## description
as for title

## how to reproduce
- put `TextOverflow` in a resizable container

## specs
- attach to the resize event and calculate the overflow on each resize

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
when parent is resized `TextOverflow` should also resize as it is a `block` (`width: 100%`): what is exactly your issue? are you sure `TextOverflow` is re-rendering after the parent has resized? (the function `verifyOverflow` is called in `componentDidUpdate` which is after each `render`)

**Comment by ascariandrea** [comment]
Yep, the component resizes on parent resizes, however the `verifyOverflow` is not called cause no re-render is caused.
Maybe it's just a matter of `@pure` decorator that wraps the component in `LOL` project.

**Comment by FrancescoCioria** [comment]
yes, it really looks like that. Try removing the `@pure` between parent and that specific `TextOverflow`
/cc @giogonzo

**Comment by ascariandrea** [comment]
I tried and it has been partially resolved.
The tooltip appears on resizing to a width minor than label's one, but it remains when I resize it to a major width.
