### ISSUE TITLE
Badge label should be react children

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#439]
because of https://github.omnilab.our.buildo.io/buildo/aliniq/issues/2787 (badge should show mixed font-weight text in the label) we need the `Badge` component to accept `ReactChildren` as label

**Comment by FrancescoCioria** [comment]
@francescogior please add requirements/specs or point to issue in lol (if it exists)

**Comment by francescogior** [comment]
@FrancescoCioria updated requirements
