### ISSUE TITLE
FocusableView: optionally debounce focus/blur events

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#455]
## requirements
In some circustances a `FocusableView` may quickly change focus 2/3 times, this causes a waterfall re-render. To avoid/mitigate the re-render waterfall we should optionally debounce blur/focus events and keep the last one

## specs
- add optional prop debounce millis
  - if it exists debounce focus/blur events with `_.debounce` (is it possible to keep only the last one?)

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
> (is it possible to keep only the last one?)

this is exactly what debounce does, right? Or I didn't get the question
