### ISSUE TITLE
BREAKING: [Button] children must be string, and code style

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#488]
Because of this code,
https://github.com/buildo/react-components/blob/master/src/button/Button.js#L126-L129
we must force `children` to be a `String` in `@prop`. The component would break if a `ReactChildren` is passed as children

**Comment by giogonzo** [comment]
Could you add a description and rationale behind this?
"Children must be Strings" could be a breaking in theory?

**Comment by francescogior** [comment]
@giogonzo ^
