### ISSUE TITLE
Components folders should all follow the same name-convention

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#492]
## requirements

components folder should follow a precise name-convention and devs should be able to guess the component folder name by knowing the component name.
## specs
- use `ComponentCase` naming (the one we're using in AlinIQ)
  - ex: `src/text-overflow/TextOverflow.js` --> **`src/TextOverflow/TextOverflow.js`**
## misc

{optional: other useful info}

**Comment by FrancescoCioria** [comment]
why is this issue part of KitchenSink macro? it seems like an internal issue to me (also very much breaking)

**Comment by ascariandrea** [comment]
Do you think this should be decoupled from other issues?
Cause it's not just a matter of style, but more a build step matter.

**Comment by FrancescoCioria** [comment]
> (also very much breaking)

after we decided to go back to npm-versioning I think we shouldn't worry anymore about this issue being breaking: we will simply publish a new breaking version.

> Do you think this should be decoupled from other issues?

Yes, it should probably become an independent issue (after all it's only sub-issue without the label "DX").

I'll do it right now
