### ISSUE TITLE
[KitchenSink] Readme generator

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#494]
← #490

## requirements
- generate component `Readme.md` by extracting documentation from component:
  - `props` definition
  -  `description` (defined as comment maybe)

## specs
- try `parse` from `tcomb-react` utility method
- implement custom `toMarkdown` function (see old one in `generateReadme.js` for help)

## misc
- https://github.com/gcanti/tcomb-react#the-tomarkdown-function

**Comment by FrancescoCioria** [comment]
we already have this working :)

![image](https://cloud.githubusercontent.com/assets/4029499/17550537/b82e812e-5ef5-11e6-9b78-fd7bd353f723.png)

The `Props` chapter is automatically generated. We should simply run `npm run generate-readmes` at each deploy and ensure that we're generating the Props chapter anytime we refresh the kitchensink on buildo/react-components

**Comment by ascariandrea** [comment]
Not mentioned in the issue:
we should be able also to define a simple description for the file to document, so we can improve the actual implementation.
