### ISSUE TITLE
[KitchenSink] Component page composition

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#495]
← #490

## requirements
- generate component doc page by:
 - use `Readme.md` inside component folder as top content (only the descriptive part, split it from the props table)
 - add `example`(s) (both `.md` and `.js` files)
 - make example editable (as they already are)
    - edit example code updates the related example preview
  - add props table (from the remaining part of `Readme.md`)

## specs
Something like: 
```
# Component name
Description

## Section 1 (example)
Section 1 description

Section 1 component preview
Section 1 code

## Props
Props table

```

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
> # Component name
Description

already like this

> ## Section 1 (example)
Section 1 description

missing

> Section 1 component preview
Section 1 code

already like this


PS: you forgot about the `Props` chapter. Right now it's at the bottom of the page and I would keep it there as it can be **really* long (at least the first example should be visible when you open the page)

**Comment by ascariandrea** [comment]
Yep, I forgot to mention that, but I agree with you: on the bottom of the page!
