### ISSUE TITLE
create Scrollable wrapper component

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#50]
requirements:
- [x] accept function content callback as `children`
  - [x] pass `scrollTo` function to callback
    - args: (x, y, time)
    - should also work on mobile
- [x] wrap content in `div` (so as usual accept `className`, `style`, `id`)
- [x] stop scroll event propagation (optional)
- [x] scroll should work properly on mobile
  - enable gravity scroll for iOS by default
- [ ] customizable scrollbar (also optional)
- [x] support every scroll direction (`overflow`)
  - only x
  - only y
  - both (default)

/cc @giogonzo @francescogior

**Comment by giogonzo** [comment]
:+1: nice

**Comment by francescogior** [comment]
:+1: great!
