### ISSUE TITLE
Update react-select to v1.0.0-rc1

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#517]
## requirements
`react-select@1.0.0-rc1` brings many new features we'd like to have in our `Dropdown` component (ex: #520, #513, autoBlur...) -> we should upgrade to v1.0.0-rc1!

## specs
- remove these hacks:
  - TODO
- fix CSS overrides (layout/CSS has changed in v1.0.0-rc1)

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
@francescogior you should probably take look at https://github.com/buildo/react-components/pull/429/files

when looking for a fix to #423 I tried to upgrade react-select to `v1.0.0-beta13` (I honestly don't remember the final result)

**Comment by giogonzo** [comment]
This should also solve the `Invalid Pointer` error we are sometimes getting when interacting with dropdowns in IE11: https://github.com/JedWatson/react-select/issues/690

**Comment by FrancescoCioria** [comment]
EDIT: replaced "-betaX" in title and specs with "-rc1" (which was released two days ago)
