### ISSUE TITLE
warning for Dropdown `placeholder`

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#520]
## description
<img width="890" alt="screen shot 2016-08-26 at 11 22 11 am" src="https://cloud.githubusercontent.com/assets/2643520/18000680/7afa4586-6b7f-11e6-9641-a93f4d008394.png">

## how to reproduce
@francescogior knows

## specs
possibly solved by https://github.com/buildo/react-components/issues/517

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
yes, solved by #517
