### ISSUE TITLE
Popover: support delay on mouse events

### ISSUE THREAD

**Issue by veej** [buildo/react-components#605]
## requirements
`Popover` should support a new `delay` prop, in order to delay the effect of mouse events. In this way we can handle the issue that cause the popover to close immediately when `onMouseLeave` is fired, preventing the user to act on popover UI (see the `hover` example in showroom)

## specs
- Take a look at `TextOverflow` that use a similar approach for delay
- Add a prop `delay` to specify the delay in milliseconds
  - should be possible to specify different delays if popover is open/closed =>  `delay: t.Number || t.struct({ whenClosed: t.Number, whenOpen: t.Number })`. Delay as a number is a shortcut to have `delayWhenClosed = delayWhenOpen = props.delay`
  - tcomb check that this prop is > 0 only if `event: 'hover'`

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
NOTE: I updated the specs to reflect the PR:
instead of having `delay.onEnter` and `delay.onLeave` we should have `delay.whenClosed` and `delayWhenOpen` as that's the real discriminator
