### ISSUE TITLE
TimePicker selection, keyboard selection and focus

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#612]
NOTE: opening this here because I feel it's related to the recent dropdown upgrade. Some or all of the issues below might be due to wrong customizations on aliniq

## description
dropdown before (hovering first line and then moving with down key):
[![https://gyazo.com/230abb2117ffa0b9f92781d843124cda](https://i.gyazo.com/230abb2117ffa0b9f92781d843124cda.gif)](https://gyazo.com/230abb2117ffa0b9f92781d843124cda)

dropdown after (hovering first row and then moving with down key):
[![https://gyazo.com/c1210bf8b8d221a3825533c9c34d1f5d](https://i.gyazo.com/c1210bf8b8d221a3825533c9c34d1f5d.gif)](https://gyazo.com/c1210bf8b8d221a3825533c9c34d1f5d)

It seems we just have an "improvement" here (the currently selected item, if any, is highlighted. The focused item is highlighted in a darker color)

timepicker before (moving with down/up keys):
[![https://gyazo.com/03645cea1695b74629c7a52c9081f62e](https://i.gyazo.com/03645cea1695b74629c7a52c9081f62e.gif)](https://gyazo.com/03645cea1695b74629c7a52c9081f62e)

timepicker after (moving with up/down keys):
[![https://gyazo.com/9315e9eaee9487db4c7f36fa4399ff1d](https://i.gyazo.com/9315e9eaee9487db4c7f36fa4399ff1d.gif)](https://gyazo.com/9315e9eaee9487db4c7f36fa4399ff1d)

we have a regression here instead:
- the first line is always highlighted even if another item is selected.
- you can't select items moving with up/down keys

Also, there's no distinction between focused and selected items

## how to reproduce
before: http://alinity-pro-sales.omnilab-development.com
after: http://qia.omnilab-development.com:3000

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
See #636 to follow know more about the "selected option background color" defect
