### ISSUE TITLE
TimePicker should allow to "localize" am/pm

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#644]
## description

Currently `am/pm` strings are hardcoded in time picker code
and there's no way to customize them from outside
## how to reproduce
- {optional: describe steps to reproduce defect}
## specs

either use `Intl` internally or accept a "timeFormatter" or both
## misc

{optional: other useful info}

**Comment by FrancescoCioria** [comment]
closed long ago by https://github.com/buildo/react-components/pull/1141
