### ISSUE TITLE
Tablo: assert on children prop is faulty

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#680]
## description
The check `Tablo` performs about the prop `children` is currently faulty

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
the length of `columnsOrGroups` should be the same `children` or, if `children` is missing, should the same of the array version of `data[0]`.

## misc
this is the incriminated line: https://github.com/buildo/react-components/blob/b12aa31c0bbc52ed8974eb4ca435ca429848ef8e/src/tablo/Tablo.js#L87

**Comment by FrancescoCioria** [comment]
@francescogior I improved title and description
