### ISSUE TITLE
Tablo: SelectionType should be optional

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#682]
## description
As indicated [here](https://github.com/buildo/react-components/blob/b12aa31c0bbc52ed8974eb4ca435ca429848ef8e/src/tablo/API.md), `selectionType` should be an optional prop, since it has a default

## how to reproduce
- do not pass `selectionType` to `Tablo`

## specs
- make it optional in the `PropTypes` declaration. The logic already handles it

**Comment by FrancescoCioria** [comment]
@francescogior what is this issue about? Why is it missing the defect template?

**Comment by francescogior** [comment]
I had opened it by `hophop gh feature create`
