### ISSUE TITLE
Dropdown: text color should not change on hover

### ISSUE THREAD

**Issue by veej** [buildo/react-components#724]
## description
Right now, when hovering over a dropdown with a value selected, the text color changes to a lighter gray.
![](https://i.gyazo.com/4f50588994068c95fc9977e2c7e53691.gif)

Using the default style, we want it to remain unchanged, and change only the background color.
It must still be possible to change the hover color via the `$text-color-hover` variable.

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
- change the default value for `$text-color-hover` to be equal to `$text-color`

## misc
{optional: other useful info}

**Comment by francescogior** [comment]
@veej @FrancescoCioria should this be considered breaking?

**Comment by veej** [comment]
It changes the default style, so technically yes, even if it's a minor change. @FrancescoCioria, what do you think?

**Comment by FrancescoCioria** [comment]
Theoretically it's breaking yes, but that's every defect/bug can be considered breaking as someone might have been relying on the defect/bug without knowing...
For practicality so far we haven't considered defects/bugs as breaking and I think we should keep consider them non-breaking unless we consider a particular fix dangerous (and CSS is usually not dangerous :) )

do you agree?
