### ISSUE TITLE
remove outside libraries from package

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#73]
I think it's more painful then useful to export external libraries. Right now we're exporting these:
- `rc-datepicker`
- `react-input-link`
- `react-autosize-textarea`
- `react-cookie-banner`

We should import them in our projects directly from their npm packages so to remove one step of synchronization

( right now I'm having problem with `npm shrinkwrap` on hailadoc because of a dffference in `react-input-link` version between global and `buildo-react-components` ... )

**Comment by FrancescoCioria** [comment]
@giogonzo can we consider this solved by https://github.com/buildo/labonline/pull/831?

**Comment by giogonzo** [comment]
possibly solved.. but for LOL only: meaning in LOL we use npm@3 and we can easily depend on both e.g. `react-components` and `react-input-link` without issues. We could do the same on HAIL I think, but it will require some time to fix things

The only change affecting this and `revenge-rect-components` is that they're now safe to be required granularly both from `src` (build required) and `lib` (no build required, pain js/css)
