### ISSUE TITLE
Tablo: redefine variables for borders

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#770]
## requirements
Borders widths and styles should be more granularly customisable.
Different variables (with default that makes sense) should be defined for:
- table borders
- cell borders
- resizer line
- header bottom borders

## specs
```
                    ---- table top border ---------------------------------
                     |      | <- fixed-columns-separator   | <- resizer-line   | <- header-cell-border |
                     | ---- header row border ---------                                                    | <-- table right border
table left border  ->|      | <- cell border      |          |   |
                    ---- row border -------------
                    |      |            |          | 
                    ----table bottom border ------
```

![img_20170224_122113](https://cloud.githubusercontent.com/assets/3280300/23301841/330adef6-fa8c-11e6-84f7-d8cfa5ae2ef7.jpg)

For each of the entities, there should be a variable for `width` and one for `color` (used as suffixes)

- `row-border` (default width: 0, default color: cell-border)
- `fixed-columns-separator` (default width is `header-cell-border * 2`, default color is `header-cell-border-color`)
- `cell-border` (default is 

border, width and color)
- `columns-resizer-line` (default is header-cell-border (width and color))
- `header-cell-border`  (the vertical border between header cells) (default is cell-border, width and color)
- `header-row-border` (the horizontal border between header and table body) (default is table border, width and color)
additionally:
- `table-border` (default width and color for the all 4 sides)

**Comment by francescogior** [comment]
@FrancescoCioria can you validate the specs?

**Comment by FrancescoCioria** [comment]
I would rename `header-border` to `header-cell-border` and `fixed-columns-separator` to `fixed-column-separator` for consistency
other than that 👍

**Comment by francescogior** [comment]
👍  for `header-cell-border` but fixed columns can be more than one!

**Comment by francescogior** [comment]
changed a little bit the specs:
- `resizer-line` => `columns-resizer-line`
- `fixed-columns-separator` default is header-cell, (width * 2)

**Comment by francescogior** [comment]
updated specs with a very nice hand-made and colorful drawing
