### ISSUE TITLE
add the ability to pass custom React context to Modal render tree

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#794]
## requirements
Currently, using `Modal` directly, there's no easy way to render components using arbitrary stuff from context inside the modal.

To be more specific, it might seem to work OK already, because this works:
```js
<Modal>
  <Component foo={this.context.foo} />
</Modal>
```
But this does not:
```js
<Modal>
  <ComponentUsingContextFoo />
</Modal>

// ComponentUsingContextFoo.js :
<View>{this.context.foo}</View>
```

Obviously the reason is that in the first example we are not relying in any way to context to be passed to the new subtree created by `ModalPortal` with `ReactDOM.render()`

Since "context needed throughout the app" is a project-specific thing, there should be a way to pass arbitrary context via `<Modal />` easily

## specs
- receive the context definition via props, and pass it via context to the new render tree created by `ModalPortal`
- since "context providers" typically are initialized passing very top level stuff (not easily available at "leaf" component level), do not require the actual data, just the types, and retrieve it directly via context

e.g.
```js
import { intlShape } from 'react-intl';
// ...
<Modal {...moreProps} childContextTypes={{ intl: intlShape }} />
```
This additional prop would be required only once when customizing the Modal component for the specific project
## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
Actually proposed specs here don't seem feasible.. I don't know how to statically declare the needed `contextTypes` if they are passed via props. So an user would be required to pass the context object too (or a context getter function)

So,

## option 1
```js
// when extending BRCModal, user is required to declare context manually
// and pass the additional props to the modal
export default class Modal extends React.Component {
  static contextTypes = {
    intl: intlShape
  };

  render() {
    const contextProps = {
      childContextTypes: {
        intl: intlShape
      },
      getChildContext: () => ({
        intl: this.context.intl
      })
    };
    return <BRCModal {...contextProps} {...this.props} />;
  }
}
```

## option 2
Slightly simplifies the above, and since it's not much code, we could add a simple helper to do this:
```js
// export this helper from BRC
const modalWithContext = contextTypes =>
  class ModalContextWrapper extends React.Component {
    static contextTypes = contextTypes;

    render() {
      const contextProps = {
        childContextTypes: contextTypes,
        getChildContext: () => this.context
      };
      return <Modal {...this.props} {...contextProps} />;
    }
  };

// use like this in the final project:
export default modalWithContext({ intl: intlShape });

// Or, if other custom props are needed,
const BRCModal = modalWithContext({ intl: intlShape });
export default class Modal extends React.Component {
  render() {
    // ...
    return <BRCModal {...moreProps} />
  }
}
```

I personally prefer the second option but it might be scary, so you choose @FrancescoCioria @veej

**Comment by FrancescoCioria** [comment]
second option is fine to me

**Comment by veej** [comment]
ok for the latter one
