### ISSUE TITLE
Tablo: readme is missing some propTypes

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#835]
## description
Missing props:
- `onColumnResize`
- `onColumnsReorder`
- ... (check if other props are missing as well)

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
manually update `tablo/README.md` (this readme is **not** automatically generated)

## misc

**Comment by FrancescoCioria** [comment]
`Tablo/README.md` only refers to `Tablo/Tablo.js` component therefore it has less props.
The complete readme is `Tablo/API.md` which is the one shown in the showroom and looks complete
