### ISSUE TITLE
Interested in cooperation?

### ISSUE THREAD

**Issue by kvolkovich-sc** [buildo/react-components#897]
Hi, guys.
See, you already have nice demo page.

It's really fun - you have [**showroom**]( http://react-components.buildo.io/), we have [**showroom**](https://github.com/OpusCapita/react-showroom-client) :laughing:

Maybe you have some interesting ideas. What kind of functionality would be nice to have, etc.
If someone of you is interested in development and improvement, lets collaborate!)

I think we'll can move our repository to neutral territory, out of our github organization.

Open-source rulez :sunglasses:

**Comment by FrancescoCioria** [comment]
Hi @kvolkovich-sc, thank you for getting in touch! 👋 

We're currently not planning to invest a lot of time in improving the showroom as it's been stable for some time and is working fine for us, but I'll definitely give your client a look!

Of course, if you want, you can try to integrate your showroom-client with our page and we'll be more than happy to see the outcome and maybe perform the switch 😊

**Comment by kvolkovich-sc** [comment]
@FrancescoCioria, I understand you. I'll try to integrate it and send you a pull request in my spare time.
