### ISSUE TITLE
Warnings while installing

### ISSUE THREAD

**Issue by gabro** [buildo/react-components#899]
## description
```
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning buildo-react-components > react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "revenge@0.4.5" has incorrect peer dependency "react@^0.13.3 || ^0.14".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 3.68s.
```

## how to reproduce
- yarn init
- yarn add react react-dom
- yarn add react-components

**Comment by FrancescoCioria** [comment]
> warning buildo-react-components > react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead.

Good to know! I wasn't aware of this

> warning "revenge@0.4.5" has incorrect peer dependency "react@^0.13.3 || ^0.14".

we're using revenge only for `skinnable` (+ `contains`) and `pure` (see https://github.com/buildo/react-components/blob/master/src/utils/index.js)
both of which now have their own repo: 
https://github.com/buildo/react-skinnable
https://github.com/buildo/react-pure

so yes, they can (and should) easily replace `revenge`

**Comment by gabro** [comment]
oh, cool. Let's do it then!
Revenge should be killed, right?

**Comment by gabro** [comment]
For the first dependency, it should be easy too.

https://www.npmjs.com/package/react-addons-transition-group
