### ISSUE TITLE
Add wrap prop to FlexView

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#90]
## Requirements
- `FlexView` should optionally let content wrap in lines
  - to avoid this ![image](https://cloud.githubusercontent.com/assets/3280300/11094814/2e9ea36a-8892-11e5-87b9-20e4d3edb583.png)
  - and let this happen 
![image](https://cloud.githubusercontent.com/assets/3280300/11094875/91c96f88-8892-11e5-8c9c-1c269dc3bcb6.png)

## Specs
- `FlexView` should have an optional `wrap` prop

Prop | Type | Required | Default
---|---|---|---
wrap | bool | no | false

**Comment by FrancescoCioria** [comment]
great!
also have a look at how `FlexView` uses classes, you should add something like:
```
&.flex-wrap {
  @include MIXIN_WITH_VALUE
}
```
